    apiVersion: v1
    kind: Service
    metadata:
      name: user-service
    spec:
      type: NodePort
      ports:
        - nodePort: 31317
          port: 8081
          protocol: TCP
          targetPort: 8081
      selector:
        app: user-app
